### ISSUE TITLE
What generates the screenshots?

### ISSUE THREAD

**Issue by fatso83** [argos-ci/argos-cli#11]
I tried to get started with Argos CI and got as far as the `/<org>/<proj>/getting-started` which landed me here. It is impossible to understand what will create the screenshots. There is just talk of uploading through the cli.

Usually something like this would require a server to generate the components on a separate page, which would then be processed by PhantomCSS or similar, etc. But this is highly project dependent stuff, and not something you touch upon at all in the material presented to the user. Which is why I have the growing suspicion that you might be able to take some shortcuts by scoping this down to some subsegment, like only projects relying on React where you can render PureComponents somehow. 

Really, I have no idea ... which is a bit of an adoption stopper :-)

**Comment by oliviertassinari** [comment]
> What generates the screenshots?

Hey @fatso83, that's an excellent question! There are many many different ways to take those screenshots. We gonna start documenting them. I like how [next.js](https://github.com/zeit/next.js/tree/v3-beta/examples) is showing a large range of integration project. Basically, here is some of the projects we want to cover.
- [wdio-visual-regression-service](https://github.com/zinserjan/wdio-visual-regression-service)
- [vrtest](https://github.com/nathanmarks/vrtest)
- [happo](https://github.com/Galooshi/happo)
- [chrome-headless-screenshots](https://github.com/schnerd/chrome-headless-screenshots/blob/master/README.md)
- [PhantomCSS](https://github.com/Huddle/PhantomCSS)

I have seen three categories of tools so far:
- The ones that take Component as input (what used with @material-ui)
- The ones that take screenshots during the e2e tests (what used with @doctolib)
- The ones that take pages as input

We don't know the best solution to this problem, we are experimenting different ones.
What's setup do you have for running tests?

**Comment by oliviertassinari** [comment]
Here is the first integration example with **wdio**: https://github.com/argos-ci/argos/pull/300.

**Comment by oliviertassinari** [comment]
Here is a second integration example with **vrtest**: https://github.com/argos-ci/argos/pull/301

**Comment by oliviertassinari** [comment]
Again some new solutions:
- **nightwatch**: https://github.com/argos-ci/argos/pull/302
- **nightmare**: https://github.com/argos-ci/argos/pull/303

**Comment by oliviertassinari** [comment]
Here is an example with **happo**: https://github.com/argos-ci/argos/pull/306.
Things I want to cover next:
- Capybara
- Protractor
- Python library?
- Static website tools?

**Comment by oliviertassinari** [comment]
Again some new solutions:
- **Protractor**: https://github.com/argos-ci/argos/pull/310
- **Rails**: https://github.com/argos-ci/argos/pull/312

**Comment by oliviertassinari** [comment]
Two new integrations:
- **Pytest**: https://github.com/argos-ci/argos/pull/313
- **Django**: https://github.com/argos-ci/argos/pull/313 (uses testunit internally)

**Comment by oliviertassinari** [comment]
Last integration I want to add before closing the issue:
- [chrome-headless-screenshots](https://github.com/schnerd/chrome-headless-screenshots)
- [Symfony](http://symfony.com/) I'm not sure it's a common pattern for them to write e2e tests.
- Find or build a static website tool

**Comment by oliviertassinari** [comment]
New integration:
 - **Storybook**: https://github.com/argos-ci/argos/pull/317

**Comment by oliviertassinari** [comment]
New integration:
 - **Chrome Headless**: https://github.com/argos-ci/argos/pull/318
